### PR TITLE
Authenticated Requests

### PR DESCRIPTION
**Pull request by rodkings**
Added ability to make Authenticated Requests. Additional work still needed on Repository.cs. A more elegant solution to UntappdCredentials  is also needed.

### CODE REVIEW

**Comment by TerribleDev** [comment]
I'll look at this when I get home in about an hour

**Comment by rodkings** [comment]
@tparnell8  thank you.

**Comment by rodkings** [comment]
oh shit, I forgot to add [Ignore] to one Test Method. =/

**Comment by TerribleDev** [comment]
the build appears to be failing on this looks like a unit test

**Comment by TerribleDev** [comment]
if you add the ignore into the branch this pull request is looking at it should trigger a new build

**Comment by rodkings** [comment]
I will do it.

**Pull request merged**
